config/routes.rb
Rails.application.routes.draw do

  get 'shows/:id/:season/:episode' => 'shows#episode'
  get 'shows/:id/:season' => 'shows#season'
  get 'shows/:id' => 'shows#show'
  get 'shows' => 'shows#index'

  get 'movies/:id' => 'movies#show'
  get 'movies' => 'movies#index'

  root 'pages#home'

end

app/models/episode.rb
class Episode < ActiveRecord::Base
  belongs_to :season
  validates :season_id, presence: true
  validates :episode_no, presence: true
  validates :file_name, {presence: true, uniqueness: true}
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  validates :file_name, {presence: true, uniqueness: true}
  validates :moviedb_id, {presence: true, uniqueness: true}

  default_scope { order('file_name ASC') } 
end

app/models/season.rb
class Season < ActiveRecord::Base
  belongs_to :show
  has_many :episodes, dependent: :destroy
  validates :show_id, presence: true
  validates :season_no, presence: true
end

app/models/show.rb
class Show < ActiveRecord::Base
  has_many :seasons, dependent: :destroy
  validates :moviedb_id, {presence: true, uniqueness: true}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :set_config
  Tmdb::Api.key("65d17b9df1ef1475d6c78956d1e0af12")

  def set_config
    @moviedb_config = Tmdb::Configuration.new

    Paginate.configure do |config|
      config.size = 5
      config.param_name = :p
    end
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    #@movies = Movie.all.order(:file_name)
    @movies = Movie.paginate(page: params[:p])
  end

  def show
    if params[:id]
      puts "Getting movie by id"
      @movie = Movie.find_by(moviedb_id: params[:id])
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  def index
    @shows = Show.all
  end

  def show
    if params[:id]
      @show = Show.find_by(moviedb_id: params[:id])
      @seasons = @show.seasons unless @show.nil?
      if @seasons && params[:season]
        @season = @seasons.find_by(season_no: params[:season])
        @episodes = @season.episodes unless @season.nil?
        if @episodes && params[:episode]
          @episode = @episodes.find_by(episode_no: params[:episode])
        end
      end
    end
  end

  def season
    if params[:id]
      @show = Show.find_by(moviedb_id: params[:id])
      @seasons = @show.seasons unless @show.nil?
      if @seasons && params[:season]
        @season = @seasons.find_by(season_no: params[:season])
      end
    end
  end

  def episode
    if params[:id]
      @show = Show.find_by(moviedb_id: params[:id])
      @seasons = @show.seasons unless @show.nil?
      if @seasons && params[:season]
        @season = @seasons.find_by(season_no: params[:season])
        @episodes = @season.episodes unless @season.nil?
        if @episodes && params[:episode]
          @episode = @episodes.find_by(episode_no: params[:episode])
        end
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  def get_movie_name(id)
    movie = Tmdb::Movie.detail(id)
    movie["original_title"]
  end

  def get_movie_poster_path(id)
    movie = Tmdb::Movie.detail(id)
    movie["poster_path"]
  end

  def get_playable_movie_url(file_name)
    "smb://192.168.1.2/nas/Media/Movies/#{file_name}"
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
  def get_show_name(id)
    movie = Tmdb::TV.detail(id)
    movie["name"]
  end

  def get_episode_name(show_id, season_no, episode_no)
    episode = Tmdb::Episode.detail(show_id, season_no, episode_no)
    "#{episode["name"]} (S#{season_no}E#{episode_no})"
  end

  def get_playable_show_url(file_name)
    "smb://192.168.1.2/nas/Media/Tv%20Shows/#{file_name}"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ems</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <h1>eLmAcNo Media Server</h1>
  </header>

  <section>
    <%= yield %>
  </section>

  <footer>
    @2015 Matias Calcagno
  </footer>

</body>
</html>

app/views/movies/_movie.html.erb
<%= link_to("movies/#{movie.moviedb_id}") do %>
  <div class='movie'>
    <%= image_tag("#{@moviedb_config.base_url}w154#{get_movie_poster_path(movie.moviedb_id)}") %>
    <!--p><%=get_movie_name(movie.moviedb_id)%></p-->
  </div>
<% end %>

app/views/movies/index.html.erb
<h2>Todas las peliculas</h2>
<%= render @movies, paginate: true %>
<div style="clear: both"></div>
<%= paginate @movies %>

app/views/movies/show.html.erb
<h2><%= get_movie_name(@movie.moviedb_id) %></h2>

<%= image_tag("#{@moviedb_config.base_url}w154#{get_movie_poster_path(@movie.moviedb_id)}") %>

<p>
  A esta pelicula <%= @movie.watched ? "" : "todavia no" %> la miraste!
  Hace click <%= link_to "aca", get_playable_movie_url(@movie.file_name) %> para mirarla<%= @movie.watched ? "de nuevo" : "" %>!
</p>

app/views/pages/home.html.erb
<h2>Bienvenidos!</h2>
<p>Que queres ver?</p>
<%= link_to "Peliculas", movies_path %>
<p>o</p>
<%= link_to "Series", shows_path %>

app/views/shows/episode.html.erb
<h2><%= get_show_name(@show.moviedb_id) %> - <%= get_episode_name(@show.moviedb_id, @season.season_no, @episode.episode_no) %></h2>

<p>
  A este episodio <%= @episode.watched ? "" : "todavia no" %> lo miraste!
  Hace click <%= link_to "aca", get_playable_show_url(@episode.file_name) %> para mirarla<%= @episode.watched ? "de nuevo" : "" %>!
</p>

app/views/shows/index.html.erb
<h2>Todas las series</h2>
<ul>
  <% @shows.each do |show| %>
    <li><%= link_to get_show_name(show.moviedb_id), "shows/#{show.moviedb_id}" %></li>
  <% end %>
</ul>

app/views/shows/season.html.erb
<h2><%= get_show_name(@show.moviedb_id) %> - Season <%= @season.season_no %></h2>
<ul>
  <% @season.episodes.each do |episode| %>
    <li><%= link_to get_episode_name(@show.moviedb_id, @season.season_no, episode.episode_no), "/shows/#{@show.moviedb_id}/#{@season.season_no}/#{episode.episode_no}" %> - <%= episode.watched ? "Mirado" : "No mirado" %></li>
  <% end %>
</ul>

app/views/shows/show.html.erb
<h2>Series</h2>
<ul>
  <% @show.seasons.each do |season| %>
    <li><%= link_to "Season #{season.season_no}", "/shows/#{@show.moviedb_id}/#{season.season_no}" %></li>
  <% end %>
</ul>